### ISSUE TITLE
login.dart 代码尚未merge

### ISSUE THREAD

**Issue by alanfit** [tencentyun/TencentIMFlutterDemo#1]
login.dart 代码尚未merge就commit了。

**Comment by hexingcheng** [comment]
请注明所遇到的问题。

**Comment by alanfit** [comment]
/lib/pages/login/login.dart
这个代码没合并好
看看我发的截图
![Jietu20210118-161957](https://user-images.githubusercontent.com/48117846/104889389-1e710300-59a9-11eb-991b-4803200bbc99.jpg)

**Comment by hexingcheng** [comment]
收到，感谢
